# Generated by Django 3.2.3 on 2021-05-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_make_appoint_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='make_appoint',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
