# Generated by Django 3.2.3 on 2021-06-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_make_appoint_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='make_appoint',
            name='status',
            field=models.CharField(default='inactive', max_length=100),
        ),
    ]
