# Generated by Django 3.2.3 on 2021-06-02 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='make_appoint',
            name='status',
        ),
    ]
